name: Auto approve and merge PRs by dependabot

# Trigger the workflow on pull request
on:
  pull_request

jobs:
  autoapprove:
    name: Auto Approve a PR by dependabot # Name of the job
    runs-on: ubuntu-latest # Environment on which the job runs
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3.1.0
        # Perform the auto approve action only when the PR is raised by dependabot
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
  automerge:
    name: Auto merge after successful checks
    # By default, jobs run in parallel. To run the jobs sequentially, they keywords "needs" is needed.
    # Auto merge action can be done only when the PR is approved, hence this automerge needs autoapprove as a prerequisite
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        # Custom action for auto merging already available on marketplace
        uses: alexwilson/enable-github-automerge-action@1.0.0        # Perform the auto merge action only when the PR is raised by dependabot
        if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
        env:
          github_token: ${{ github.token }}
          # By default, whenever dependabot raises a PR, it automatically assigns a label named "dependencies"
          # So, this action merges those PRs labelled "dependencies" only
          MERGE_LABELS: dependencies
          MERGE_METHOD: rebase
